# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a19c3e7f5567df7ea4e7c8f4b15dda82ab87b6b08957f497b5813c7e90dd34dade4d82b3861f92c4d785f15110e1bc7eaee45095868715f02dd32c2bfef341c5

test:
  secret_key_base: 2ddff4c765ccd720c3c7b3c3235bac912dc1333c4d9f5752a80223e486cee915d8e233d23afd7e74068265aa2253e657c0a7a14e61720693e0d75929b408d758

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
